version: 1.0.{build}
image: Visual Studio 2017

before_build:
# - dotnet restore

build_script:
- ps: |
    $f=[io.file]::Open((Get-Location).Path+"/install.msi",3)
    $f.SetLength(1200000000)
    $f.Close()
    Write-Output "Branch: $env:APPVEYOR_REPO_BRANCH"
    $env:sign="true"
    Write-Output $env:sign 
     
# - dotnet build /verbosity:quiet "avtest.sln"
# Testfile

artifacts:
- path: install.msi

deploy:
- provider: Webhook
  url: https://fqa.test.signpath.io/API/v1/6c1f5fa2-0824-4b5e-b3d9-66f51f58467b/Integrations/AppVeyor?ProjectSlug=Appveyor_integration&SigningPolicySlug=LegacyAppVeyor&ArtifactConfigurationSlug=Default

  authorization:
     secure: fxY5R02XJ8g2rRkxzhHJ3Pc9FDv2PqB4RRpHDAsfn9KcN0IXY8cWvVCV/ojJc/QYEEzkZMlfHp+1cXaHHAXdyA==

  on:
    sign: true

