version: 1.0.{build}
image: Visual Studio 2017

before_build:
# - dotnet restore

build_script:
- ps: |
    $f=[io.file]::Open((Get-Location).Path+"/install.msi",3)
    $f.SetLength(2100000000)
    $f.Close()
    Write-Output "Branch: $env:APPVEYOR_REPO_BRANCH"
    $env:sign="true"
    Write-Output $env:sign 
     
# - dotnet build /verbosity:quiet "avtest.sln"
# Testfile

artifacts:
- path: npgsql.4.0.3.nupkg

environment:
  SIGNPATH_ORGANIZATION_ID: d2ad3ea0-54b4-42c8-8e74-d8d6d00ece2e
  SIGNPATH_PROJECT_SLUG: NuGet_AppVeyor
  SIGNPATH_SIGNING_POLICY_SLUG: NuGet_AppVeyor
  ARTIFACT_CONFIGURATION_SLUG: initial
  SIGNPATH_CI_USER_TOKEN:
    secure: zvTFfmMdFLEHzxXQWlqasiK14RF1dAujsd57mD8+VGyc1+WW6X1a7SkyIHgUPCAG

deploy:
- provider: Webhook
  #url: https://fqa.test.signpath.io/API/v1/6c1f5fa2-0824-4b5e-b3d9-66f51f58467b/Integrations/AppVeyor?ProjectSlug=Appveyor_integration&SigningPolicySlug=LegacyAppVeyor&ArtifactConfigurationSlug=Default
  url: https://appveyor.connectors.dev.signpath.io:15001/api/sign?OrganizationId=%SIGNPATH_ORGANIZATION_ID%&test=1&ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%


  authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
     # secure: fxY5R02XJ8g2rRkxzhHJ3Pc9FDv2PqB4RRpHDAsfn9KcN0IXY8cWvVCV/ojJc/QYEEzkZMlfHp+1cXaHHAXdyA==
     # --> AEHM8QqisPaQIso9F8S1D8x+Me3COLlN+RHbLiH58Fw9?

  on:
    sign: true

